version: 0.2

env:
  variables:
    AWS_REGION: us-east-2
    ACCOUNT_ID: "558627362683"
    ECR_REPO_NAME: "mixergtz/uniandes-blacklist-service"
    CONTAINER_NAME: "uniandes-blacklist-container"

phases:
  install:
    commands:
      - echo "Instalando uv..."
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.local/bin:$PATH"
      - uv --version || echo "uv instalado"

  pre_build:
    commands:
      - echo "Login Docker Hub..."
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - echo "Login en ECR..."
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - echo "Instalando dependencias del proyecto..."
      - uv sync --no-dev --frozen

      - echo "Ejecutando pruebas unitarias..."
      - uv run pytest -v

      - echo "Configurando tags de la imagen..."
      - COMMIT_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - echo "IMAGE_URI=$IMAGE_URI"
      - echo "COMMIT_TAG=$COMMIT_TAG"

  build:
    commands:
      - echo "Construyendo imagen AMD64..."
      - docker build -t $IMAGE_URI:$COMMIT_TAG .
      - docker tag $IMAGE_URI:$COMMIT_TAG $IMAGE_URI:latest

      - echo "Haciendo push a ECR..."
      - docker push $IMAGE_URI:$COMMIT_TAG
      - docker push $IMAGE_URI:latest

  post_build:
    commands:
      - echo "Generando imageDetail.json para ECS..."
      - printf '{"ImageURI":"%s"}' "$IMAGE_URI:$COMMIT_TAG" > imageDetail.json
      - cat imageDetail.json

artifacts:
  files:
    - taskdef.json
    - appspec.json
    - imageDetail.json
  discard-paths: yes
